CHANGELOG.md, framework.go, go.mod, pkg/client/client.go, pkg/wait/conditions.go
CAPG clusters have their kubeconfig generated using the IP address of the GCP load balancer but this isn't routable over our VPN so results in failure when running locally. This change ensure that any kubeconfig found to be using the IP address hostname is instead changed to use the DNS name built up from the `baseDomain` for the cluster.
=> Update kubeconfig to always use dns hostname for server

CHANGELOG.md, pkg/application/app_test.go
Specify a version to use in the App unit tests so they don't attempt to call out to GitHub for the latest release.
=> Fix App tests

CHANGELOG.md, README.md, doc.go, framework.go, pkg/client/client.go
This allows for providing a single Kubeconfig for use by the framework that contains different context. This can be used for having multiple MCs in a single kubeconfig and have the test suites switch to the appropriate context (MC) for their tests.
My thinking here is there will be a kubeconfig provided to the test suites that contain context such as `capa`, `capvcd`, etc. which would allow for running the entire collection of test suites together.
=> Support multiple context in MC kubeconfig

CHANGELOG.md, README.md, pkg/application/app.go, pkg/application/app_test.go, pkg/application/cluster_app.go, pkg/application/doc.go
Slightly tweak the App version logic to support overriding the version from an environment variable when set to `""` (empty string).
The env var name must match a specific format consisting of a standard prefix and a modification of the app name, E.g. for `cluster-aws` the env var would be `E2E_OVERRIDE_CLUSTER_AWS` and if none is found then the same logic as `latest` is used.
=> Enable overriding app version with env var

.nancy-ignore, CHANGELOG.md, pkg/application/app.go, pkg/application/app_test.go, pkg/application/doc.go, pkg/application/utils.go
Unfortunately Tekton doesn't allow for dynamically setting the name property of an env var in a pod so we need to have a static, known name to use for overriding.
The added benefit of this is it's easier / cleaner from a CI/CD perspective to provide multiple overrides in a single run.
=> Change version override to use a single env var

CHANGELOG.md, doc.go, framework.go
Towards https://github.com/giantswarm/giantswarm/issues/26378
This lets the caller to load a WC from the targeted MC. This is done by setting the `E2E_WC_NAME` and `E2E_WC_NAMESPACE` env vars. The framework will get the App and values ConfigMap and set up and return the Cluster struct.
=> Add LoadCluster function

.gitignore, pkg/application/app.go, pkg/application/cluster_app.go
because the cluster App cr for vsphere looks like this:
```
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
labels:
app-operator.giantswarm.io/version: 0.0.0
app.kubernetes.io/name: cluster-vsphere
name: $CLUSTER
namespace: org-giantswarm
spec:
catalog: cluster-test
extraConfigs:
- kind: secret
name: container-registries-configuration
namespace: giantswarm
priority: 25
kubeConfig:
inCluster: true
name: cluster-vsphere
namespace: org-giantswarm
userConfig:
configMap:
name: $CLUSTER-user-values
namespace: org-giantswarm
secret:
name: vsphere-credentials
namespace: org-giantswarm
version: 0.3.1-689cef7898e90f8184ac526369dddf119d9a0af2
```
so we need a way to change the 
```
...
secret:
name: vsphere-credentials
...
```
chunk
=> User config secret name of cluster app

CHANGELOG.md, framework.go
Towards: https://github.com/giantswarm/giantswarm/issues/26823
Ensure that the Org and all other resources associated with the E2E test run are cleaned up before completing.
Note: This change will likely increase the amount of false failures we see.
=> Wait for org delete to complete

CHANGELOG.md, pkg/wait/conditions.go
Rather than something like `Checking if resource 't-vwbnapj' still exists` that could be either the Cluster or the Organization, this change updates the log message to use the resources 'Kind' rather than just `resource` to make it clear which resource we're waiting for.
=> Include resource kind in wait log message

CHANGELOG.md, framework.go, pkg/client/client.go, pkg/wait/conditions.go
- `CreateOrUpdate` function added to the kube client that allows you to create or overwrite the given resource in the cluster.
- `IsAppStatus` and `IsAppVersion` wait conditions to check for an app being in an expected release status and expected version deployed.
- `GetApp` function to get an App resource from the MC
- `GetConfigMap` function to get a ConfigMap from the MC
- `ApplyCluster` can now be called again with an updated Cluster resource to update the Apps in the MC
- `GetAppAndValues` now takes in a context argument to be consistent with the other helper functions
=> Added more helper functions

CHANGELOG.md, pkg/application/app.go, pkg/utils/github.go
Towards: https://github.com/giantswarm/giantswarm/issues/27743
Adds support for a `GITHUB_TOKEN_FILE` environment variable so its possible to mount a secret containing the GitHub token as a volume that can be updated when the access token is renewed.
The support for the `GITHUB_TOKEN` environment variable still takes precedence if set.
=> Support GITHUB_TOKEN_FILE env var

.gitignore, CHANGELOG.md, framework.go, pkg/application/app.go, pkg/application/app_test.go, pkg/application/cluster_app.go, pkg/application/cluster_app_test.go, pkg/application/doc.go, pkg/organization/organization.go
We found out that `kubectl-gs` logic won't use the `Namespace` field when setting `InCluster` to false. In that case, it uses the `Organization`,  so we need to be able to set it.
=> Allow to set application organization

CHANGELOG.md, pkg/application/types.go, pkg/application/types_test.go
This PR adds a custom unmarshaller to the `NodePools` type to check if the raw json begins with a `[` or not and based on that decides to unmarshal it as an array (and build a map from it) or a map.
=> Update ClusterValues to handle unmarshalling both NodePools types

CHANGELOG.md, pkg/wait/conditions.go
Related to: https://github.com/giantswarm/giantswarm/issues/28065
This PR adds a new `WaitCondition` helper function that allows checking the status of a list of Apps all at once. E.g. this could be used for checking all default-apps are deployed.
=> Added IsAllAppStatus WaitCondition helper function

CHANGELOG.md, pkg/application/app.go, pkg/application/app_test.go, pkg/application/github.go
Towards: https://github.com/giantswarm/giantswarm/issues/28066
When an App name doesn't match the name used for the repo because of an `-app` suffix we'll attempt to find the alternative if we couldn't find the releases with the provided name.
=> Check for '-app' suffix variation when getting latest releases

pkg/application/app.go, pkg/application/app_test.go
Fixes: https://github.com/giantswarm/giantswarm/issues/28066
Generally this shouldn't be needed but if we happen to have an App that has a very different repo name this will allow setting it manually to ensure getting the latest version still works as expected.
=> Support overriding the App repo name

CHANGELOG.md, pkg/application/app.go, pkg/application/app_test.go
Fixes: https://github.com/giantswarm/giantswarm/issues/28067
Adds more config used when installing apps into workload clusters rather than the management cluster. This exposes setting the `Cluster` property that's used to populate labels and allows setting a `Namespace` that the app contents will be installed into.
This PR also introduces a fix for the kubeconfig context name generated by kubectl-gs to actually be the one used by CAPI.
=> Improve Application to allow installing into workload clusters

CHANGELOG.md, framework.go, pkg/client/client.go
Fixes: https://github.com/giantswarm/giantswarm/issues/28029
Added `DeployApp` helper function that ensures an Apps CR and ConfigMap are deployed in the correct order.
=> Added DeployApp helper function

CHANGELOG.md, pkg/application/app.go, pkg/application/app_test.go, pkg/client/client.go
- Correctly set the namespace on Applications
- Added a `GetInstallNamespace` helper function for Application
- Added `DeleteApp` helper function to remove an App CR and its ConfigMap from the cluster
=> Fixes for broken App deployments

CHANGELOG.md, pkg/client/client.go
Towards https://github.com/giantswarm/roadmap/issues/2351
We also need this for CAPA clusters if we want to use our VPN to access them.
=> Use custom DNS for k8s api in kubeconfig

CHANGELOG.md, pkg/wait/wait.go
This PR reduces the DefaultTimeout by half to discourage the use of it in place of more relevant values. Based on data collected form the past week worth of runs on Tekton, no individual step took longer than 30 minutes so this should be safe to drop. 
I'll be doing a change to `cluster-test-suites` shortly after this is released to update the dependancy and replace the current references to `DefaultTimeout` with more appropriate timeouts for each task.
Towards: https://github.com/giantswarm/giantswarm/issues/28028
=> Reduce DefaultTimeout to 30 minutes

CHANGELOG.md, framework.go, pkg/client/client.go, pkg/testuser/doc.go, pkg/testuser/resources.go, pkg/testuser/template.go, pkg/testuser/testuser.go, pkg/wait/conditions.go, pkg/wait/doc.go
To support EKS clusters, and any other that might require time-limited kubeconfig credentials, the test framework now creates a ServiceAccount with `cluster-admin` permissions in the workload cluster and creates a kubernetes client that authenticates as that account.
Along with the new `testuser` package that handles the creation of the resources and the generation of a new kube client we also introduce the following changes:
* `client.NewFromSecret` - helper function to get a kubeconfig from the known kubeconfig secret in an MC
* `client.GetAPIServerEndpoint` - Returns the API server URL, used when generating the new kubeconfig
* `wait.IsClusterReadyCondition` - no longer mutates the frameworks list of WC clients
=> Switch to using ServiceAccount auth for WC kube client

CHANGELOG.md, pkg/testuser/testuser.go
This change ensures that the testuser ServiceAccount is only created once in the Workload Cluster so that conflicts aren't faced when re-calling the `ApplyCluster` function, for example during the upgrade tests.
=> Ensure the testuser ServiceAccount is only created once

CHANGELOG.md, pkg/application/types.go, pkg/application/types_test.go
The schema used by cluster apps are changing to move most of the values under a `global` property but it's going to take a while before all providers are updated to the new schema so we need a way of seamlessly handling both schemas without causing too much impact on the tests themselves. This change introduces a custom unmarshaller that checks which schema version we are working with and generate a `ClusterValues` object from their values.
=> Add custom unmarshaller to handle new and old schema

.nancy-ignore, CHANGELOG.md, pkg/application/app.go, pkg/application/app_test.go
If we have set a different catalog using `WithCatalog()` we should use that as the base for the test catalog if we're automatically overriding it based on a sha-based version number.
This only happens if the provided catalog doesn't already end in `-test`
=> Update WithVersion() logic to better set the test catalog

.nancy-ignore, CHANGELOG.md, pkg/application/app.go
The kubectl-gs code that generates an Application CR (and ConfigMap) doesn't handle an empty values string and will instead panic. This adds a guard against it by ensuring that empty values values are replaced with a single newline character which is enough for the kubectl-gs code to work with.
=> Safely handle an empty values file

CHANGELOG.md, framework.go, go.mod, go.sum, pkg/wait/conditions.go
This PR adds the following new `WaitCondition` funcs:
- `IsClusterConditionSet` checks if Cluster resource has a condition set with specified status and reason
- `IsKubeadmControlPlaneConditionSet` checks if KubeadmControlPlane resource has a condition set with specified status and reason
And also:
- `GetKubeadmControlPlane` that returns KubeadmControlPlane resource that is used in cluster-test-suites to do checks with KubeadmControlPlane resource
These will be then used in cluster-test-suites suites to:
- check if the Cluster has Ready condition with Status=True
- check a control plane rolling update has finished by checking if KubeadmControlPlane has MachinesSpecUpToDate condition with Status=True
=> Add WaitConditions to check for Cluster API status conditions

CHANGELOG.md, pkg/client/client.go, pkg/client/exec.go, pkg/wait/conditions.go
See separate commits.
When looking at test output, I want to see _why_ something failed. Otherwise, the logs are pretty much useless and I have to rerun and look at the E2E cluster _while the test is running_. My changes make the output more actionable by adding more info (finalizers, reason for app status, errors).
Tested locally in cluster-test-suites with `replace github.com/giantswarm/clustertest => ../clustertest`.
=> Improve test logging to make errors actionable

CHANGELOG.md, pkg/client/client.go, pkg/client/exec.go, pkg/wait/conditions.go
Switch to using single quotes around variables to make them more readable in the log output in Tekton.
Example of before:
```
{"level":"info","ts":"2024-05-09T10:54:25Z","msg":"App status for t-42ahb6yuuobyg4o37a-aws-pod-identity-webhook is not yet as expected: expectedStatus=\"deployed\" actualStatus=\"\" (reason: \"\")"}
{"level":"info","ts":"2024-05-09T10:54:25Z","msg":"App status for t-42ahb6yuuobyg4o37a-capi-node-labeler is as expected: deployed"}
```
Example of after:
```
{"level":"info","ts":"2024-05-09T10:54:25Z","msg":"App status for 't-42ahb6yuuobyg4o37a-aws-pod-identity-webhook' is not yet as expected: expectedStatus='deployed' actualStatus='' (reason: '')"}
{"level":"info","ts":"2024-05-09T10:54:25Z","msg":"App status for 't-42ahb6yuuobyg4o37a-capi-node-labeler' is as …
```
=> Switch to using single quotes

CHANGELOG.md, pkg/application/types.go
Blocked by:
* https://github.com/giantswarm/cluster-test-suites/pull/291
* https://github.com/giantswarm/ingress-nginx-app/pull/628
Remove the `DefaultAppsValues` struct in favour of using the cluster values instead. The only property it supported was `BaseDomain` which is also already available on the Cluster values.
This goes a small way in making the migration to not having default-apps anymore a little bit easier.
=> Remove DefaultAppsValues struct

CHANGELOG.md, framework.go, go.mod, pkg/application/app.go, pkg/application/app_test.go, pkg/application/cluster_app.go
Towards https://github.com/giantswarm/roadmap/issues/3119
With cluster-aws v0.76.0 and newer, default apps are deployed with cluster-aws and default-apps-aws app is not deployed anymore.
Note: The latest cluster-aws release is v0.75.0 and the [default apps addition](https://github.com/giantswarm/cluster-aws/pull/581) is not yet merged (but it has been tested and it's ready to be merged). This PR assumes that the [default apps addition](https://github.com/giantswarm/cluster-aws/pull/581) will be merged and that v0.76.0 will be released.
=> Support unified cluster-aws app

CHANGELOG.md, pkg/application/cluster_app.go, pkg/application/utils.go, pkg/organization/organization.go
Towards: https://github.com/giantswarm/giantswarm/issues/26830
Blocked by: https://github.com/giantswarm/tekton-resources/pull/343
If specific Tekton env vars are found we'll populate labels on App and Org CRs to point to the relevant PipelineRun and TaskRun to make it easier to find out what test run created what resources.
=> Include PipelineRun and Taskrun name in App labels

CHANGELOG.md, framework.go, pkg/application/cluster_app.go
Added a new `ApplyBuiltCluster` function that allows building a `BuiltCluster` within a test case and then having that applied to the MC instead of re-building it within `ApplyCluster`. This allows us to use `cluster.Build()` within the upgrade test and ensure that the values we're referencing in the test case are the same as being applied to the MC.
=> Added new ApplyBuiltCluster framework function

CHANGELOG.md, pkg/wait/conditions.go
Towards: https://github.com/giantswarm/giantswarm/issues/31013
Adds some extra logging that will display the taints of all current nodes being checked against so the actual progress of the nodes can be seen in the test logs.
```
{"level":"info","ts":"2024-06-20T10:27:14+01:00","msg":"Checking for ready nodes"}
{"level":"info","ts":"2024-06-20T10:27:14+01:00","msg":"2 nodes ready, expecting 3"}
{"level":"info","ts":"2024-06-20T10:27:14+01:00","msg":"Node status: NodeName='ip-10-0-108-44.eu-west-2.compute.internal', Taints='[{node-role.kubernetes.io/control-plane  NoSchedule <nil>}]'"}
{"level":"info","ts":"2024-06-20T10:27:14+01:00","msg":"Node status: NodeName='ip-10-0-147-166.eu-west-2.compute.internal', Taints='[{node-role.kubernetes.io/control-plane  NoSchedule <nil>} …
```
=> Added extra logging to node ready check when condition fails

CHANGELOG.md, go.mod, go.sum, pkg/client/client.go
Towards: https://github.com/giantswarm/giantswarm/issues/31130
Adds the cert-manager types to the kube client so we can use `.Get()` to get things like `Certificates` and `ClusterIssuers`
=> Added cert-manager schema to kube client

CHANGELOG.md, README.md, framework.go, pkg/application/app_test.go, pkg/application/cluster_app.go, pkg/application/utils.go, pkg/env/const.go
Towards: https://github.com/giantswarm/roadmap/issues/3477
Example output:
```
E2E_RELEASE_VERSION=aws-25.0.0-mntest.3 E2E_RELEASE_COMMIT=522aa35f2e7d9576147cb1bad70b44ec7b323df7 E2E_KUBECONFIG=~/.kube/clusters/e2e.yaml ginkgo --timeout 4h -v -r ./providers/capa/standard/
Running Suite: CAPA Standard Suite - /Users/marcus/Code/GiantSwarm/cluster-test-suites/providers/capa/standard
==============================================================================================================
Will run 32 of 32 specs
------------------------------
[BeforeSuite] 
/Users/marcus/Code/GiantSwarm/cluster-test-suites/internal/suite/setup.go:25
{"level":"info","ts":"2024-06-25T15:53:58+01:00","msg":"Workload cluster name: t-oxu827vi4m3j2xz3v1"} …
```
=> Add support for Release override env vars

CHANGELOG.md, pkg/client/events.go, pkg/client/events_test.go
Towards: https://github.com/giantswarm/giantswarm/issues/31142
Added helper functions to the Client type that allows getting all current events related to the given resource.
=> Added helpers to get Events for given resource

CHANGELOG.md, pkg/client/client.go, pkg/client/client_test.go, pkg/client/logs.go, pkg/client/logs_test.go
Added a couple new helper functions:
* Get all pods associated with a given Deployment
* Get logs from a given Pod
=> Added helpers for logs and pods in deployment

CHANGELOG.md, pkg/failurehandler/apps.go, pkg/failurehandler/doc.go, pkg/failurehandler/types.go
Adds a new package to be used with Gomega assertions to perform extra debugging when they fail.
Example:
```
Eventually(wait.IsAllAppDeployed(state.GetContext(), state.GetFramework().MC(), appNamespacedNames)).
WithTimeout(timeout).
WithPolling(10*time.Second).
Should(
BeTrue(),
failurehandler.AppIssues(state.GetContext(), state.GetFramework(), state.GetCluster()),
)
```
Example result (with long logs removed for brevity)
```
{"level":"info","ts":"2024-06-28T11:36:53+01:00","msg":"Attempting to get debug info for App related failure"}
{"level":"info","ts":"2024-06-28T11:36:53+01:00","msg":"Checking 't-rn2nxm3pxapqevel8f-app-operator' on Management Cluster"}
{"level":"info","ts":"2024-06-28T11:36:53+01:00","msg":"Deployment 'app-operator' status - Name='t-rn2nxm3pxapqevel8f-app-operator', …
```
=> Added `failurehandler` package

CHANGELOG.md, README.md, pkg/application/cluster_app.go, pkg/env/const.go
Towards: https://github.com/giantswarm/roadmap/issues/3537
Refactor the way Releases are handled in code to allow for more complex version overriding logic. 
This change introduces 3 possible states that can be handled:
1. The release version is set to `""` - This will make use of the environment variable overrides if found or default to the latest version
2. The release version is set to `latest` - This will instruct the code not to use the env vars and instead always use the latest released version
3. The release version is set to a specific value (and commit sha) - Use that version, usually from a PR on the releases repo
This brings the logic inline with how `E2E_OVERRIDE_VERSIONS` is handled and allows us to build support for upgrade tests.
=> Refactor release handling

CHANGELOG.md, README.md, pkg/env/const.go
Towards: https://github.com/giantswarm/giantswarm/issues/31134
Note, this env var is already used by cluster-standup-teardown but is being moved here for consistency and documentation purposes.
=> Added the E2E_WC_KEEP env var constant

CHANGELOG.md, pkg/net/const.go, pkg/net/dns.go, pkg/net/httpclient.go
Towards: https://github.com/giantswarm/giantswarm/issues/31135
Make an initialised DNS and HTTP client available to be used within tests. An external nameserver is configured in both to help avoid negative DNS caching and the http client will make use of the proxy if one is detected.
=> Added dns and http clients

CHANGELOG.md, pkg/utils/upgrade.go
We need to also use `ShouldSkipUpgrade` in `cluster-standup-teardown` so i'm moving it into here to be able to be referenced from both repos.
=> Moved ShouldSkipUpgrade from cluster-test-suites

CHANGELOG.md, pkg/client/client.go, pkg/failurehandler/apps.go, pkg/failurehandler/context.go, pkg/failurehandler/daemonsets.go, pkg/failurehandler/deployments.go, pkg/failurehandler/statefulsets.go
Added:
- New failurehandler functions: `DeploymentsNotReady`, `DaemonSetsNotReady` & `StatefulSetsNotReady`
- Added `GetPodsForStatefulSet` and `GetPodsForDaemonSet` to client
> [!WARNING]
> This PR introduces a breaking change to the `AppIssues` function to no longer take in a Context object. Even with this I plan to release this as a minor release and will be fixing the only place this code is used immediately after this is released.
=> Added failurehandlers for Deployments, STS and DaemonSets

CHANGELOG.md, go.mod, pkg/application/app.go, pkg/application/cluster_app.go, pkg/application/defaultAppsValues.go, pkg/application/github.go
Towards: https://github.com/giantswarm/roadmap/issues/3095
- Fixed `isShaVersion` regex to also allow for versions with pre-release suffix already (e.g. `-gs3`)
- Replaced `getLatestReleaseVersion` with `GetLatestAppVersion` so it can be used outside of the module
- Log output of release name now handled in `Build` instead of `GetRelease` so `GetRelease` can be called in tests without causing confusing logs (as name is unique each time)
- Added `IsDefaultApp` to Cluster to allow checking if a given App is a default app installed for that cluster
- Added `WithAppOverride` to Cluster to allow overriding default apps included on a Release (note: only supports providers that have moved to Releases already)
=> Support overriding default apps in Releases

CHANGELOG.md, pkg/wait/conditions.go
Fixes https://github.com/giantswarm/giantswarm/issues/30463
No longer return an error if failed to get kubeconfig secret for something like a network blip. Instead log out the error and return `false` so it can be retried on the next iteration. The check also not ensures that the provided context hasn't already expired.
Example output:
```
{"level":"info","ts":"2024-08-06T08:11:14+01:00","msg":"kubeconfig secret not yet available"}
{"level":"info","ts":"2024-08-06T08:11:24+01:00","msg":"Checking for valid Kubeconfig for cluster t-tz4qffdzjugds8degi"}
{"level":"info","ts":"2024-08-06T08:11:24+01:00","msg":"kubeconfig secret not yet available"}
{"level":"info","ts":"2024-08-06T08:11:34+01:00","msg":"Checking for valid Kubeconfig for cluster t-tz4qffdzjugds8degi"} …
```
=> More resilient check for kubeconfig secret

CHANGELOG.md, pkg/application/app.go, pkg/application/app_test.go
Towards https://github.com/giantswarm/roadmap/issues/3125
> [!CAUTION]
> cluster-vsphere v0.61.0 is not yet released.
> 
> cluster-vsphere v0.61.0 with default apps will be released once [this PR](https://github.com/giantswarm/cluster-vsphere/pull/262) has been merged. Only then clustertest with this change can be used.
Add support for unified cluster-vsphere app. With cluster-vsphere v0.61.0 and newer, default apps are deployed with cluster-vsphere, and default-apps-vsphere app is not deployed anymore.
=> Add support for unified cluster-vsphere app

CHANGELOG.md, pkg/application/cluster_app.go
Signed-off-by: Matias Charriere <matias@giantswarm.io>
- Remove `v` prefix from App version for Releases.
- Add app version and catalog to log
Otherwise I get:
```
[FAILED] Unexpected error:
<*errors.errorString | 0xc000b163d0>: 
failed to apply release resources: [Release.release.giantswarm.io](http://release.release.giantswarm.io/) "aws-29.2.0-t.bhtzeft1ch" is invalid: spec.apps[7].version: Invalid value: "v0.27.0-3569e5fe41d64e0a07a7ff73308f436ff86ac9b0": spec.apps[7].version in body should match '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
{
s: "failed to apply release resources: [Release.release.giantswarm.io](http://release.release.giantswarm.io/) …
```
=> Remove "v" prefix from App Version for Releases

CHANGELOG.md, pkg/client/client.go
This allows using the current framework setup code without having to provide the context to use from the kubeconfig. This will be used for MC testing where the kubeconfig produced by mc-bootstrap is passed through to the test suite and the context name is unknown without extra work.
=> Fallback to default context if empty context name provided

CHANGELOG.md, framework.go, pkg/failurehandler/jobs.go
This PR adds a new failure handler that will print out more debug info for failed Jobs within the cluster.
This PR also makes a change to the way the framework gets WC clients to allow a fallback to the MC if the cluster name asked for isn't found but matched the name of the MC. This allows us to use a lot of the existing framework function for MC testing without a big refactor right now.
=> Add a new failure handler for Jobs and allow getting MC as WC

CHANGELOG.md, framework.go, pkg/application/cluster_app.go, pkg/application/provider.go
Fixes: https://github.com/giantswarm/giantswarm/issues/31588
Make sure that the `Provider` field on a loaded Cluster is set based on the cluster app being used by that cluster.
Note: This change also introduces a new `ProviderUnknown` to allow a fallback value to be returned but currently it shouldn't be possible for this value to be used under normal testing.
Manually tested with the `apptest-framework` basic test suite. 
```
{"level":"info","ts":"2024-10-08T11:20:51+01:00","msg":"Overriding 'latest' version to '2.4.0'"}
Running Suite: Basic Test - /Users/marcus/Code/GiantSwarm/apptest-framework/tests/e2e/suites/basic
==================================================================================================
Random Seed: 1728382836
Will run 5 of 5 specs …
```
=> Ensure Provider is populated when loading an existing workload cluster

CHANGELOG.md, pkg/failurehandler/types.go
Needed to be able to cleanly use multiple different FailureHandlers in a single gomega assertion.
=> Added Bundle function to using multiple FailureHandlers together

CHANGELOG.md, pkg/client/client.go
Old message:
```
{"level":"info","ts":"2024-12-03T11:09:45Z","msg":"Error occurred while trying to get kubeconfig secret - kubeconfig secret found but data[kubeconfig.yaml] not populated"}
```
New message:
```
{"level":"info","ts":"2024-12-03T11:09:45Z","msg":"Error occurred while trying to get kubeconfig secret - kubeconfig secret 'teleport-t-XXXX-kubeconfig' found in namespace 'org-t-XXXX' but data[kubeconfig.yaml] not populated"}
```
=> Improve error message when KubeConfig data not populated

CHANGELOG.md, pkg/wait/conditions.go
Towards: https://github.com/giantswarm/giantswarm/issues/32317
Adds a new Wait function that allows checking for pods that have containers restarting too many times.
=> Added wait function to check for CrashLooping pods

CHANGELOG.md, pkg/wait/wait.go
We were previously ignoring any deadline set on the provided context instance. This first checks if one is set and if not then use the timeout.
=> Correctly handle context with deadline set

CHANGELOG.md, pkg/wait/waitconditionslice.go
A set of new WaitCondition functions that can return a slice of failing resources rather than just a true/false boolean result.
This allows more useful test failure messages.
=> Introduce new slice-based WaitConditions
