- README.md
- doc.go
- framework.go
- pkg/application/app.go
- pkg/application/cluster_app.go
- pkg/application/doc.go
- pkg/application/utils.go
- pkg/client/client.go
- pkg/client/doc.go
- pkg/logger/doc.go
- pkg/logger/logger.go
- pkg/organization/doc.go
- pkg/organization/organization.go
- pkg/utils/doc.go
- pkg/utils/string_utils.go
- pkg/wait/doc.go
- pkg/wait/wait.go
These docs can be previewed here: https://pkg.go.dev/github.com/giantswarm/clustertest@v0.0.3-0.20230321151100-d4ad96c961c5
Fixes https://github.com/giantswarm/roadmap/issues/2078
> Updated and filled out documentation (godoc)

- .circleci/config.yml
- .nancy-ignore
- CHANGELOG.md
- pkg/application/app.go
- pkg/application/utils.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/organization/organization.go
- pkg/utils/string_utils.go
- Lint issues (ignored returns)
- Added CircleCI configuration for linting and unit tests
- Added some ignores for nancy until a fix is available for the vulnerabilities
> Added CircleCI tests

- pkg/wait/conditions.go
Will be used here https://github.com/giantswarm/cluster-test-suites/pull/15
As discussed in planning it makes more sense to have it in here.
> Add Consistent function

- CHANGELOG.md
- pkg/client/options.go
- pkg/wait/conditions.go
Also use variadic list options when checking that nodes are ready.
Towards https://github.com/giantswarm/cluster-test-suites/pull/19
> Add DoesNotHaveLabels

- CHANGELOG.md
- go.mod
- pkg/application/app.go
Help to avoid rate limiting when fetching the latest releases of Apps from GitHub.
> Make use of GITHUB_TOKEN env var if found

- CHANGELOG.md
- pkg/application/cluster_app.go
> add-eks-provider

- CHANGELOG.md
- pkg/client/exec.go
needed by some in-development tests
> Add possibility to exec a command in a pod.

- CHANGELOG.md
- pkg/client/client.go
Towards https://github.com/giantswarm/giantswarm/issues/30298
> Added GetClusterName function to get name from kubeconfig

- CHANGELOG.md
- pkg/wait/conditions.go
Fixes https://github.com/giantswarm/giantswarm/issues/29932
> Improve reliability of cluster deletion

- .circleci/config.yml
- .golangci.yaml
- pkg/application/cluster_app.go
- pkg/application/types.go
- pkg/client/events.go
- pkg/client/exec.go
- pkg/net/const.go
- pkg/utils/github.go
- pkg/wait/conditions.go
Fixes https://github.com/giantswarm/giantswarm/issues/27242
> Enable linting of doc comments

- CHANGELOG.md
- pkg/application/cluster_app.go
- pkg/application/utils.go
- pkg/organization/organization.go
- pkg/utils/env.go
Populate more details in labels provided from the CICD pipelines on the Cluster and Org resources
> Support more default base labels from CICD env vars

- .circleci/config.yml
- CHANGELOG.md
- go.mod
Towards: https://github.com/giantswarm/giantswarm/issues/31630
> Bump Go version to v1.23.1

- CHANGELOG.md
- pkg/application/github.go
Fixes: https://github.com/giantswarm/giantswarm/issues/31690
> Correctly get latest GitHub release for Apps

- CHANGELOG.md
- pkg/wait/conditions.go
These are mostly taken from `cluster-test-suite` and changes slightly to return a `WaitCondition` so that they can be re-used in different test suites.
Towards: https://github.com/giantswarm/roadmap/issues/2930
> Added some generic cluster-wide WaitConditions

- CHANGELOG.md
- pkg/failurehandler/pods.go
Added helper for better debugging of why Pods might not be running successfully.
> Added failurehandler for non-ready Pods

- CHANGELOG.md
- pkg/client/logs.go
- pkg/failurehandler/pods.go
- Correctly handle pointer in log output
- Clean up some debug log output and continue loop on error
> Handle pointer correctly in debug logging

- CHANGELOG.md
- pkg/application/app.go
- pkg/application/app_test.go
towards https://github.com/giantswarm/giantswarm/issues/31701
> add support for cluster-cloud-director as a unified app

- CHANGELOG.md
- framework.go
Fixes: https://github.com/giantswarm/giantswarm/issues/32217
> Handle E2E_WC_KEEP in framework when deleting a cluster

- framework.go
- pkg/client/client.go
- pkg/wait/conditions.go
- pkg/wait/doc.go
Towards https://github.com/giantswarm/giantswarm/issues/33940.
> Conditions: Make `IsClusterReadyCondition` return the client.

- framework.go
Make it clearer which stage of cluster creation was problematic by wrapping each error with a description
> Improve cluster creation error logging

- CHANGELOG.md
- pkg/failurehandler/helmreleases.go
Towards https://github.com/giantswarm/cluster-test-suites/pull/787
> Add failureHandler for HelmReleases that are not Ready

- CHANGELOG.md
- pkg/client/client.go
This is required [for this to work](https://github.com/giantswarm/cluster-test-suites/pull/801).
> Use v2 for helm CRs
